package mobile.android.testapplication.network

object WebserviceUrls {
    // Apis base urls
    internal val GOOGEL_PLACES = "https://maps.googleapis.com/maps/api/place/"
   // internal val BASE_URL = "http://quickease.elintminds.work/api/"
    internal val BASE_URL = "https://picsum.photos/v2/"
    internal val TERM_CONDITION_URL = "https://quickeasemobile.com/pages/terms-and-conditions"
    internal val PRIVACY_POLICY_URL = "https://quickeasemobile.com/pages/privacy-policy"
    internal val BASE_URL_IMAGES = "https://quickeasemobile.com/"
    internal val GIF_IMAGES_URL = "https://media.giphy.com/media/xT9IgMgdur6larNA1a/giphy.gif"
    const val APP_CONFIGRATION_API = "appconfigration"
    const val LOGIN_API = "login"
    const val SOCIAL_LOGIN_API = "sociallogin"
    const val FORGOT_PASSWORD_API = "forgotpassword"
    const val REGISTER_API = "register2"
    const val CHANGE_PASSWORD_API = "changepassword"
    const val LOGOUT_API = "logout"
    const val EDIT_PROFILE_API = "editprofile"
    const val USER_ADDRESSES_API = "useraddresses"
    const val REMOVE_USER_ADDRESSES_API = "removeaddress"
    const val SAVE_ADDRESSES_API = "saveaddress"
    const val SAVE_VEHICLE_API = "savevehicle"
    const val REMOVE_VEHICLE_API = "removevehicle"
    const val GET_USER_VEHICLE_API = "uservehicle"
    const val GET_PACKAGES_API = "getpackages"
    const val GET_ADDONS_API = "getaddons"
    const val GET_PROMO_CODE_API = "getPromocode"
    const val CHECK_ADDRESS_DISTANCE_API = "checkaddressdistance"
    const val CONFIRM_APPOINTMENT_API = "confirmAppointment"
    const val SAVE_APPOINTMENT_API = "saveAppointment"
    const val GET_APPOINTMENT_API = "getAppointment"
    const val CANCEL_APPOINTMENT_API = "cancelAppointment"
    const val RESCHEDULE_APPOINTMENT_API = "rescheduleAppointment"
    const val CHECK_CHARGES_API = "checkCharges"
    const val SAVE_RATING_API = "saveRatingReview"
    const val SAVE_CARDS_API = "saveCard"
    const val GET_CARDS_API = "getCards"
    const val GET_VEHICLE_MAKER_API = "getMakes"
    const val GET_VEHICLE_MAKER_MODEL_API = "getMakesModel"
    const val PAY_FOR_APPOINTMENT_API = "payForAppointment"
    const val GET_WEEKLY_DISCOUNT_API = "getWeeklyDiscount"
    const val CHECK_DISTANCE = "checkdistance"
    const val CHANGE_CLAIM_REWARD_STATUS_API = "changeclaimreward"
    const val GET_ADDRESS_TAG_API = "getaddressestag"
    const val GET_FULL_ADDRESS_BYTAG_ID_API = "getaddressesbytagid"
    const val GET_NOTIFICATIONS_API = "getnotifications"
    const val TIME_SLOT_API = "gettimeslots"
    const val DATE_SLOT_API = "getdatesslots"
    const val GET_PROFILE_API = "userprofile"
    const val GET_BANNER_IMAGE = "bannerimage"
    const val PAST_BOOKING_PAY = "pastbookingpay"
    const val EMAIL_RESEND = "resend"
    const val EDIT_APOINTMENT_API = "updateBooking"


}
